Plugins/RawCMS.Plugin.Core/Controllers/LambdaController.cs, Plugins/RawCMS.Plugins.Auth/UserCheckLambda.cs, RawCMS.Library/Core/AppEngine.cs
**Related task:** no task related
fix: rest lambas wasn't load properly due to the scope assembly selection. now all assembly with plugin and  the entry assembly are scanned for lambda.
fix: lambda controller had a wrong type case and lambda selection
nothing
=> fix: rest lambas wasn't load properly 

Dockerfile
=> fix on docker file

RawCMS.Client/BLL/Core/ConfigFile.cs
Signed-off-by: Francesco Minà <mina.francesco@gmail.com>
=> remove filepath config file

RawCMS.Client/BLL/Services/ConfigService.cs
Signed-off-by: Francesco Minà <mina.francesco@gmail.com>
- [ x] BUGFIX
remove absolute path for config file, used only for testing
=> remove absolute path for config file, used only for testing

README.md
**Related task:** https://github.com/arduosoft/RawCMS/issues/84
Fixed several spelling/gramamr mistakes to improve quality and reading experience of readMe.
=> Fixed Issue #84 Updated README.md

README.md
Spelling : edit link in readme.
=> Readme spelling

raw-cms-app/.prettierignore, raw-cms-app/.prettierrc.json, raw-cms-app/.vscode/settings.json, raw-cms-app/package-lock.json, raw-cms-app/package.json, raw-cms-app/src/app/app.js, raw-cms-app/src/app/app.tpl.html, raw-cms-app/src/app/events.js, raw-cms-app/src/modules/core/assets/i18n/i18n.en.json, raw-cms-app/src/modules/core/components/entities-list/entities-list.css, raw-cms-app/src/modules/core/components/entities-list/entities-list.js, raw-cms-app/src/modules/core/components/entities-list/entities-list.tpl.html, raw-cms-app/src/modules/core/services/entities-schema.service.js, raw-cms-app/src/modules/core/services/snackbar-service.js, raw-cms-app/src/modules/core/views/entities/entities.tpl.html
**Related task:** partly resolve #68 
- Add Prettier for code style
- Add husky and pretty-quick for code style
- Add snackbar to app wireframe to send message to user
- Add delete button with confirm dialog on entities schema list
=> Delete entity from schema

RawCMS/Startup.cs
- [x ] ENANCHEMENT
Enable cors
=> Enable cors

raw-cms-app/src/config/router.js, raw-cms-app/src/modules/core/assets/i18n/i18n.en.json, raw-cms-app/src/modules/core/components/collection-item-details/collection-item-details.js, raw-cms-app/src/modules/core/components/collection-item-details/collection-item-details.tpl.html, raw-cms-app/src/modules/core/views/collection-item-details-view/collection-item-details-view.js, raw-cms-app/src/modules/core/views/collection-item-details-view/collection-item-details-view.tpl.html
**Related task:** (part of) #70
Add page to edit/create new item in a collection.
=> Add page to add/edit item in collection.

raw-cms-app/src/modules/core/components/collection-item-details/collection-item-details.js
=> Edit form field validation

raw-cms-app/src/modules/core/assets/i18n/i18n.en.json, raw-cms-app/src/modules/core/components/entity-details/entity-details.js, raw-cms-app/src/modules/core/components/entity-details/entity-details.tpl.html
**Related task:** none
- Fix add new entity
- Add "name" and "allow not mapped fields" to entity details
None
=> Fix add new entity

raw-cms-app/src/modules/core/assets/i18n/i18n.en.json, raw-cms-app/src/modules/core/views/collection-table-view/collection-table-view.js, raw-cms-app/src/modules/core/views/collection-table-view/collection-table-view.tpl.html
=> filter improvment

docs/Setup-Dev.md, docs/index.md
=> add setup for development

raw-cms-app/src/modules/core/components/collection-item-details/collection-item-details.tpl.html, raw-cms-app/src/modules/core/components/dashboard/dashboard.tpl.html, raw-cms-app/src/modules/core/components/lambda-details/lambda-details.tpl.html, raw-cms-app/src/modules/shared/components/charts/simple-pie-chart/simple-pie-chart.js, raw-cms-app/src/styles.css
**Related task:** none
Some minor fixes and Vue warnings removal.
=> Minor ui fixes

docker/Dockerfile-ui
=> docker file

docker/Dockerfile-ui
=> docker fix

docker/config/ui/bootstrap.sh, raw-cms-app/src/config/router.js
=> support ga

README.md
=> release ga

docs/Deploy.md
=> bring back spelling errors

README.md, raw-cms-app/src/config/vuetify.js
**Related task:** <https://github.com/arduosoft/RawCMS/issues/184>
Changed the primary color from blue.darken2 to indigo.darken4
n/a
=> Issue #184

docs/Troubleshooting.md
- [X ] ENHANCEMENT
**Related task:** 
#206 - Review documentation of Throubleshooting page
I renamed the file to troubleshooting. I focused on replacing a few words for better clarity and fixing minor grammar issues. 
There wasn't any specific tasks here. I saw a request for suggestions/edits to this file and I saw some things that could be cleaned up.
=> Minor edits for the troubleshooting.md file

docs/Tutorial.md
Fixed spelling errors and added alt tags to images for better accessibility
- [X ] ENANCHEMENT
https://github.com/arduosoft/RawCMS/issues/208
Documentation updating and copywriting
on your pull requests notes, if you look up a few lines at "Describe here thecnical detail omitted on task " is thecnical supposed to be technical? Could be a possible typo.
=> Documentation update

CONTRIBUTING.md
- [ *] BUGFIX
**Related task:** Not applicable
All changes are simple typos with the exception of the changes to the second sentence of line 73. I may have changed the intended meaning of this sentence since I'm not sure what it was originally trying to say.
=> Corrected grammatical and spelling errors

Plugins/RawCMS.Plugins.Core/Configuration/AuthConfig.cs, Plugins/RawCMS.Plugins.Core/Configuration/ExternalProvider.cs, Plugins/RawCMS.Plugins.Core/Configuration/RawCMSProvider.cs
**Related task:** https://github.com/arduosoft/RawCMS/issues/216
The OAuthMode enum is now in ExternalProvider.cs file
=> AuthConfig refactoring

raw-cms-app/src/modules/core/services/metadata.service.js
**Related task:** https://github.com/arduosoft/RawCMS/issues/175
Unused options type fields were removed
=> #175 - Remove unused options type fields

RawCMS/conf/NLog.Development.config
**Related task:**
https://github.com/arduosoft/RawCMS/issues/204
=> Addresses #204 - Logpath changed to root source folder.

README.md
**Related task:** https://github.com/arduosoft/RawCMS/issues/251
Describe here technical detail omitted on task
Most of the edits made were typographical errors, but for a few there were changes to the general language to elevate the first viewing of the ReadMe.
=>  grammar edits, some rephrasing, and adjustments to spacing/alignment

docs/BackgroundJobs.md
Describe here technical detail omitted on task
Fixed few typo errors and grammatical mistakes.
=> Updated BackgroundJobs.md

docs/Authentication.md, docs/BackgroundJobs.md
Describe here technical detail omitted on task
Fixed some grammatical and typo errors.
=> Updated Authentication.md

azure-pipelines.yml
Disable sonarcloud integration on azure pipeline
=> Sonarcloud
